/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package nmcandroid.nmcandroid;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int blue=0x7f050000;
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int addresses=0x7f020001;
        public static final int arrow_white_down=0x7f020002;
        public static final int arrow_white_up=0x7f020003;
        public static final int bg_aopen_00_splashscreen=0x7f020004;
        public static final int bkbusiness=0x7f020005;
        public static final int bkcatalogs=0x7f020006;
        public static final int bkcoupons=0x7f020007;
        public static final int bkproducts=0x7f020008;
        public static final int blue=0x7f020009;
        public static final int bookmark=0x7f02000a;
        public static final int business=0x7f02000b;
        public static final int card_american_express=0x7f02000c;
        public static final int card_discover=0x7f02000d;
        public static final int card_master_card=0x7f02000e;
        public static final int card_visa=0x7f02000f;
        public static final int cards=0x7f020010;
        public static final int catalogs=0x7f020011;
        public static final int choose_account=0x7f020012;
        public static final int compose_new_message=0x7f020013;
        public static final int contact_us=0x7f020014;
        public static final int coupons=0x7f020015;
        public static final int cvacia=0x7f020016;
        public static final int e=0x7f020017;
        public static final int gradient=0x7f020018;
        public static final int gradient2=0x7f020019;
        public static final int gradientgray1=0x7f02001a;
        public static final int gradientgray2=0x7f02001b;
        public static final int gradientgreenbars1=0x7f02001c;
        public static final int gradientgreenbars2=0x7f02001d;
        public static final int gradientmenu=0x7f02001e;
        public static final int green=0x7f02001f;
        public static final int icon=0x7f020020;
        public static final int language=0x7f020021;
        public static final int loyalty_settings=0x7f020022;
        public static final int memberships=0x7f020023;
        public static final int n=0x7f020024;
        public static final int n_e=0x7f020025;
        public static final int n_o=0x7f020026;
        public static final int notification=0x7f020027;
        public static final int o=0x7f020028;
        public static final int red=0x7f020029;
        public static final int remoteproducts=0x7f02002a;
        public static final int report_abuse=0x7f02002b;
        public static final int s=0x7f02002c;
        public static final int s_e=0x7f02002d;
        public static final int s_o=0x7f02002e;
        public static final int scan_time_out=0x7f02002f;
        public static final int search=0x7f020030;
        public static final int shintaro_logo=0x7f020031;
        public static final int terms=0x7f020032;
        public static final int textfield_default=0x7f020033;
        public static final int user_info=0x7f020034;
        public static final int work=0x7f020035;
    }
    public static final class id {
        public static final int bAddNewAddressConfirmar=0x7f07000c;
        public static final int bChooseAcount=0x7f070026;
        public static final int bConfirmEditCard=0x7f070021;
        public static final int bEdit=0x7f07003c;
        public static final int bUserInfoConfirmar=0x7f070049;
        public static final int button2=0x7f070027;
        public static final int button3=0x7f07002b;
        public static final int button4=0x7f07002c;
        public static final int eTAddNewAddressLabel=0x7f070003;
        public static final int eTAddNewAddressStreet1=0x7f070008;
        public static final int eTAddNewAddressStreet2=0x7f07000a;
        public static final int eTAddNewAddressType=0x7f070006;
        public static final int eTAddNewAddressZipCode=0x7f07000b;
        public static final int eTChooseAcountFilter=0x7f070023;
        public static final int eTEditCardBillingAddress=0x7f07001d;
        public static final int eTEditCardBillingZipCode=0x7f07001f;
        public static final int eTEditCardCcvCode=0x7f07001a;
        public static final int eTEditCardExpiration=0x7f070017;
        public static final int eTEditCardLabel=0x7f07000e;
        public static final int eTEditCardNameOnCard=0x7f070011;
        public static final int eTEditCardNumber=0x7f070014;
        public static final int eTEditCardType=0x7f07000f;
        public static final int eTUserInfoDateOfBirth=0x7f070044;
        public static final int eTUserInfoEmailAddress=0x7f070045;
        public static final int eTUserInfoFirstName=0x7f070042;
        public static final int eTUserInfoLastName=0x7f070043;
        public static final int eTUserInfoMobileNumber=0x7f070046;
        public static final int eTUserInfoMobilePinCode=0x7f070048;
        public static final int eTUserInfoPassword=0x7f070047;
        public static final int edtEmail=0x7f07003d;
        public static final int edtPassword=0x7f07003e;
        public static final int imageButton1=0x7f070022;
        public static final int imageButton2=0x7f070025;
        public static final int infoBillingAddress=0x7f070039;
        public static final int infoBillingAddressZipCode=0x7f07003b;
        public static final int infoCardLabel=0x7f07002d;
        public static final int infoCardNumber=0x7f070033;
        public static final int infoCardType=0x7f07002f;
        public static final int infoCcvCode=0x7f070037;
        public static final int infoExpirationDate=0x7f070035;
        public static final int infoNameOnCard=0x7f070031;
        public static final int linearLayout1=0x7f070020;
        public static final int myButton=0x7f07003f;
        public static final int pgbLoad=0x7f070040;
        public static final int tMessage=0x7f070041;
        public static final int tUserInfo=0x7f070000;
        public static final int tableLayout1=0x7f07000d;
        public static final int tableLayout2=0x7f070024;
        public static final int tableLayout3=0x7f070028;
        public static final int tableRow1=0x7f070001;
        public static final int tableRow2=0x7f070004;
        public static final int tableRow3=0x7f070007;
        public static final int tableRow4=0x7f070009;
        public static final int tableRow5=0x7f070012;
        public static final int tableRow6=0x7f070015;
        public static final int tableRow7=0x7f070018;
        public static final int tableRow8=0x7f07001b;
        public static final int textView10=0x7f070029;
        public static final int textView11=0x7f07002a;
        public static final int textView19=0x7f070002;
        public static final int textView20=0x7f070005;
        public static final int textView21=0x7f070010;
        public static final int textView22=0x7f070013;
        public static final int textView23=0x7f070016;
        public static final int textView24=0x7f070019;
        public static final int textView25=0x7f07001c;
        public static final int textView26=0x7f07001e;
        public static final int textView27=0x7f07002e;
        public static final int textView29=0x7f070030;
        public static final int textView31=0x7f070032;
        public static final int textView42=0x7f070034;
        public static final int textView44=0x7f070036;
        public static final int textView46=0x7f070038;
        public static final int textView48=0x7f07003a;
    }
    public static final class layout {
        public static final int addnewaddress=0x7f030000;
        public static final int editcard=0x7f030001;
        public static final int history=0x7f030002;
        public static final int infocard=0x7f030003;
        public static final int login=0x7f030004;
        public static final int main=0x7f030005;
        public static final int splash=0x7f030006;
        public static final int switchsettingstext=0x7f030007;
        public static final int userinfo=0x7f030008;
    }
    public static final class string {
        public static final int app_name=0x7f040002;
        public static final int edit1_text=0x7f040003;
        public static final int edit2_text=0x7f040004;
        public static final int hello=0x7f040001;
        public static final int library_name=0x7f040000;
    }
    public static final class style {
        public static final int GreenHeader=0x7f060000;
        public static final int NormalRowText=0x7f060002;
        public static final int WhiteSubHeader=0x7f060001;
        public static final int red_edittext=0x7f060003;
    }
}
