using System;

//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Address.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//

namespace DTO
{
    public class Address
    {
        public String Label { get; set; }
        public AddressType Type { get; set; }
        public String _Street1 { get; set; }
        public String Street2 { get; set; }
        public String ZipCode { get; set; }

    }
}