//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : BookmarkCategory.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//

namespace DTO
{


    public enum BookmarkCategory
    {
        Business,
        Coupons,
        Catalogs,
        Products
    }
}