//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Bookmark.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//

using System.Collections.Generic;
using System.Collections;

namespace DTO
{


    public class Bookmark : PurchaseItem
    {
        public BookmarkCategory Category { get; set; }

    }
}