//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Card.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//
using System;


namespace DTO
{

    public class Card
    {
        public String Label { get; set; }
        public CardType Type { get; set; }
        public String NameOnCard { get; set; }
        public String CardNumber { get; set; }
        public DateTime Expiration { get; set; }
        public String CCV { get; set; }
        public String BillingAddress { get; set; }
        public String BillingZipCode { get; set; }

    }
}