//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : PurchaseItem.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//
using System;
using System.Collections;
using System.Collections.Generic;

namespace DTO
{


    public class PurchaseItem
    {
        public String QRCode { get; set; }
        public Decimal UnitPrice { get; set; }
        public int Quantity { get; set; }

        /// <summary>
        /// Lista de opciones a escoger para un producto
        /// </summary>
        public List<OptionalProducts> Options { get; set; }

    }
}