//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : PaymentItem.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//
using System;

namespace DTO
{


    public class PaymentItem
    {
        public Card Card { get; set; }
        public Decimal Ammount { get; set; }

    }
}