//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : NotificationType.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//
namespace DTO
{
    
    public enum NotificationType
    {
        Beep,
        BeepVibrate,
        Off
    }

}