//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//
using System;
using System.Collections.Generic;

namespace DTO
{
    public class User
    {
        public String Email { get; set; }
        public String Password { get; set; }
        public String Pin { get; set; }
        public List<Address> AddressList { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public String MobileNumber { get; set; }
        public List<Card> CardList { get; set; }
        public List<Bookmark> BookmarkList { get; set; }

    }
}