//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : CardType.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//

namespace DTO
{


    public enum CardType
    {
        AmericanExpress,
        MasterCard,
        Visa,
        Discover
    }
}