#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("NMCAndroid.Resource", IsApplication=true)]

namespace NMCAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			DTO.Resource.String.library_name = NMCAndroid.Resource.String.library_name;
			BRL.Resource.String.library_name = NMCAndroid.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int countries_array = 2131034112;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int addresses = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_white_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow_white_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_Aopen_00_Splashscreen = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BkBusiness = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BkCatalogs = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BkCoupons = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int BkProducts = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blue = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Bookmark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Business = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int card_american_express = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int card_discover = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int card_master_card = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int card_visa = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cards = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Catalogs = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int choose_account = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int compose_new_message = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int contact_us = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Coupons = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Cvacia = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int e = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int gradient = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int gradient2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int gradientGray1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int gradientGray2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int gradientGreenBars1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int gradientGreenBars2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int gradientMenu = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int green = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int history_blue = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int history_green = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int history_red = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Icon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int language = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int loyalty_settings = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Memberships = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int n = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int n_e = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int n_o = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int notification = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int o = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int red = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int RemoteProducts = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int report_abuse = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int RoundShape = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int RoundShapeFront = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int s = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int s_e = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int s_o = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int scan_time_out = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int search = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int shintaro_logo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int terms = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int textfield_default = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int user_info = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int work = 2130837562;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int bAddNewAddressConfirmar = 2131165198;
			
			// aapt resource value: 0x7f070023
			public const int bConfirmEditCard = 2131165219;
			
			// aapt resource value: 0x7f070044
			public const int bEdit = 2131165252;
			
			// aapt resource value: 0x7f070051
			public const int bUserInfoConfirmar = 2131165265;
			
			// aapt resource value: 0x7f070001
			public const int button1 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int eTAddNewAddressLabel = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int eTAddNewAddressStreet1 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int eTAddNewAddressStreet2 = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int eTAddNewAddressType = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int eTAddNewAddressZipCode = 2131165197;
			
			// aapt resource value: 0x7f07001f
			public const int eTEditCardBillingAddress = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int eTEditCardBillingZipCode = 2131165217;
			
			// aapt resource value: 0x7f07001c
			public const int eTEditCardCcvCode = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int eTEditCardExpiration = 2131165209;
			
			// aapt resource value: 0x7f070010
			public const int eTEditCardLabel = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int eTEditCardNameOnCard = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int eTEditCardNumber = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int eTEditCardType = 2131165201;
			
			// aapt resource value: 0x7f070026
			public const int eTFiltro = 2131165222;
			
			// aapt resource value: 0x7f07004c
			public const int eTUserInfoDateOfBirth = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int eTUserInfoEmailAddress = 2131165261;
			
			// aapt resource value: 0x7f07004a
			public const int eTUserInfoFirstName = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int eTUserInfoLastName = 2131165259;
			
			// aapt resource value: 0x7f07004e
			public const int eTUserInfoMobileNumber = 2131165262;
			
			// aapt resource value: 0x7f070050
			public const int eTUserInfoMobilePinCode = 2131165264;
			
			// aapt resource value: 0x7f07004f
			public const int eTUserInfoPassword = 2131165263;
			
			// aapt resource value: 0x7f070045
			public const int edtEmail = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int edtPassword = 2131165254;
			
			// aapt resource value: 0x7f070028
			public const int iVChooseAccount = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int iVFiltro = 2131165221;
			
			// aapt resource value: 0x7f07002d
			public const int iVLogo = 2131165229;
			
			// aapt resource value: 0x7f070041
			public const int infoBillingAddress = 2131165249;
			
			// aapt resource value: 0x7f070043
			public const int infoBillingAddressZipCode = 2131165251;
			
			// aapt resource value: 0x7f070035
			public const int infoCardLabel = 2131165237;
			
			// aapt resource value: 0x7f07003b
			public const int infoCardNumber = 2131165243;
			
			// aapt resource value: 0x7f070037
			public const int infoCardType = 2131165239;
			
			// aapt resource value: 0x7f07003f
			public const int infoCcvCode = 2131165247;
			
			// aapt resource value: 0x7f07003d
			public const int infoExpirationDate = 2131165245;
			
			// aapt resource value: 0x7f070039
			public const int infoNameOnCard = 2131165241;
			
			// aapt resource value: 0x7f070024
			public const int lLContenedor = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int linearLayout1 = 2131165218;
			
			// aapt resource value: 0x7f070047
			public const int myButton = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int pgbLoad = 2131165256;
			
			// aapt resource value: 0x7f070000
			public const int spinner = 2131165184;
			
			// aapt resource value: 0x7f070034
			public const int tLDetailItem = 2131165236;
			
			// aapt resource value: 0x7f070049
			public const int tMessage = 2131165257;
			
			// aapt resource value: 0x7f070002
			public const int tUserInfo = 2131165186;
			
			// aapt resource value: 0x7f070029
			public const int tVChooseAccount = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int tVChooseAcountAll = 2131165226;
			
			// aapt resource value: 0x7f070031
			public const int tVCodigoFecha = 2131165233;
			
			// aapt resource value: 0x7f07002f
			public const int tVDireccion = 2131165231;
			
			// aapt resource value: 0x7f070032
			public const int tVFecha = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int tVHora = 2131165235;
			
			// aapt resource value: 0x7f070030
			public const int tVTelefono = 2131165232;
			
			// aapt resource value: 0x7f07002e
			public const int tVTienda = 2131165230;
			
			// aapt resource value: 0x7f07000f
			public const int tableLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070027
			public const int tableLayout2 = 2131165223;
			
			// aapt resource value: 0x7f07002b
			public const int tableLayout3 = 2131165227;
			
			// aapt resource value: 0x7f070003
			public const int tableRow1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int tableRow2 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int tableRow3 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow4 = 2131165195;
			
			// aapt resource value: 0x7f070014
			public const int tableRow5 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int tableRow6 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int tableRow7 = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int tableRow8 = 2131165213;
			
			// aapt resource value: 0x7f07002c
			public const int textView18 = 2131165228;
			
			// aapt resource value: 0x7f070004
			public const int textView19 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int textView20 = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int textView21 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int textView22 = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int textView23 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int textView24 = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int textView25 = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int textView26 = 2131165216;
			
			// aapt resource value: 0x7f070036
			public const int textView27 = 2131165238;
			
			// aapt resource value: 0x7f070038
			public const int textView29 = 2131165240;
			
			// aapt resource value: 0x7f07003a
			public const int textView31 = 2131165242;
			
			// aapt resource value: 0x7f07003c
			public const int textView42 = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int textView44 = 2131165246;
			
			// aapt resource value: 0x7f070040
			public const int textView46 = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int textView48 = 2131165250;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Acordeon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddNewAddress = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditCard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int History = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HistoryDetail = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InfoCard = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Splash = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SwitchSettingsText = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int UserInfo = 2130903050;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int prompt = 2130968579;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int EditTextGray = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
