//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : DeliveryType.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//


namespace DTO
{

    public enum DeliveryType
    {
        Delivery,
        PickUp
    }
}