//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCart.cs
//  @ Date : 19/11/2012
//  @ Author : 
//
//
using System.Collections;
using System.Collections.Generic;

namespace DTO
{

    public class ShoppingCart
    {
        public List<Purchase> PurchaseList;
    }
}